### ISSUE TITLE
[FEAT] implement

### ISSUE THREAD

**Issue by suhyun113** [suhyun113/Pygame_breakOut#1]
### 🏝️Issue
> 구현하고자 하는 함수의 이슈 개요를 입력해주세요.

### 📆 Development Period
> 2024.11.13~2024.11.27

### 🖥️ Todo
implements.py 구현
- [x] 초기 세팅(2024.11.13)
- [x] alive() 함수 구현(2024.11.22)

뭔가 망해서 branch 다시 팝니다...
- [x] hit_wall() 함수 구현(2024.11.25)
- [x] collide_block() 함수 구현(2024.11.26)
- [x] collide() 함수 구현(2024.11.27)

*주의 : 파일 수정은 implements.py의 (#TODO: ) 부분만 가능

### 🧩 Etc.(선택)
 > 기타사항 (참고할 만한 자료, 참고했던 자료, 궁금한 점 등)
